title: Astral Forge
description: Astral Forge is a video game development company with a passion for creating immersive story-driven worlds for our players to explore and enjoy!
keywords: Astral Forge, Video Games, AstralForge, Games, Fates Loop, Astral Forge Games, RPG, Role Playing Games, Indie Company
url: astralforge.co.uk

include: ["_redirects"]
keep_files: ["_redirects"]